config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  resources :rconfigs
  resources :systemfailures
  get  '/adduser',  to: 'users#new'
  get  '/systemfailureupload',  to: 'systemfailures#systemfailureupload'
  root 'static_pages#home'
  get  'static_pages/home'
  post '/adduser',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :systemfailures do
    collection { post :import }
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/systemfailure.rb
class Systemfailure < ApplicationRecord




  def self.search(search) #self.でクラスメソッドとしている

    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      Systemfailure.where(reporter: search)
    else
      Systemfailure.all #全て表示。
    end
  end


  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      if row["systemfailure_number"]
        # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
        systemfailure = find_by(systemfailure_number: row["systemfailure_number"]) || new
        # CSVからデータを取得し、設定する
        systemfailure.attributes = row.to_hash.slice(*updatable_attributes)
        # 保存する
        systemfailure.save
      end
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["systemfailure_number", "subsystem_name", "time", "title", "occur_date", "department", "reporter", "occurrence_year", "occurrence_month"]
  end
end

app/controllers/systemfailures_controller.rb
class SystemfailuresController < ApplicationController
  before_action :admin_user, only: [:index, :edit, :update]
  
  def index
    @systemfailures = Systemfailure.search(params[:selectuser])
    @users = User.all
  end

  def show
    @systemfailure = Systemfailure.find(params[:id])
  end

  def new
    @systemfailure = Systemfailure.new
  end

  def create
    @systemfailure = Systemfailure.new(params[:id])
    @systemfailureshistory = Systemfailureshistory.new(params[:id])
    if @systemfailure.save
      if @systemfailureshistory.save
        flash[:success] = "登録成功しました。"
      else
        flash[:success] = "登録が成功しました。※履歴登録が失敗しました。"
      end
      log_in @systemfailure
      redirect_to @systemfailure
    else
      render 'new'
    end
  end

  def edit
    @systemfailure = Systemfailure.find(params[:id])
  end

  def update
    @systemfailure = Systemfailure.find(params[:id])
    if @systemfailure.update_attributes(systemfailure_params)
      @systemfailureshistory = Systemfailureshistory.new(params[:id])
      if systemfailureshistory.save
        flash[:success] = "保存成功しました。"
      else
        flash[:success] = "保存成功しました。※履歴登録が失敗しました。"
      end
      redirect_to systemfailures_path
    else
      render 'edit'
    end
  end

  def destroy
    Systemfailure.find(params[:id]).destroy
    flash[:success] = "ユーザを削除しました。"
    redirect_to users_url
  end

  def import
    # fileはtmpに自動で一時保存される
    Systemfailure.import(params[:file])
    redirect_to systemfailures_path
  end

  private

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def systemfailure_params
      params.require(:systemfailure).permit(:time, 
:occur_date, 
:title, 
:department, 
:reporter, 
:update_deadline,
:confirm_deadline, 
:signal, 
:status, 
:hayakawa_comment, 
:chargecomment, 
:exchange_status, 

:hayakawa_show, 
:report_path, 
:followup, 
:evidence_update, 
:overall_check, 
:quality_status, 

:occurrence_year, 
:quality_status, 
:occurrence_month, 

:recurrence_Preventday)
    end

end

app/views/systemfailures/_form.html.erb
    <%= form_for(@systemfailure) do |f| %>
      <%= render 'shared/systemfailure_error_messages' %>

      <%= f.label :障害番号 %>
      <%= f.text_field :systemfailure_number , class: 'form-control',readonly: true%>

      <%= f.label :サブシステム %>
      <%= f.text_field :subsystem_name, class: 'form-control' ,readonly: true%>

      <%= f.label :時点 %>
      <%= f.text_field :time , class: 'form-control'%>

      <%= f.label :発生日時 %>
      <%= f.text_field :occur_date, class: 'form-control' %>

      <%= f.label :表題 %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :部署 %>
      <%= f.text_field :department, class: 'form-control' %>

      <%= f.label :報告者 %>
      <%= f.text_field :reporter, class: 'form-control' %>

      <%= f.label :記入期限 %>
      <%= f.text_field :update_deadline, class: 'form-control' %>

      <%= f.label :確定期限 %>
      <%= f.text_field :confirm_deadline, class: 'form-control' %>

      <%= f.label :シグナル %>
      <%= f.text_field :signal, class: 'form-control' %>

      <%= f.label :ステータス %>
      <%= f.text_field :status, class: 'form-control' %>

      <%= f.label :早川さんコメント欄 %>
      <%= f.text_field :hayakawa_comment, class: 'form-control' %>

      <%= f.label :担当コメント欄 %>
      <%= f.text_field :chargecomment, class: 'form-control' %>

      <%= f.label :やりとりステータス %>
      <%= f.text_field :exchange_status, class: 'form-control' %>

      <%= f.label :早川さんにご覧いただき %>
      <%= f.text_field :hayakawa_show, class: 'form-control' %>

      <%= f.label :報告書保存先 %>
      <%= f.text_field :report_path, class: 'form-control' %>

      <%= f.label :フォローアップ欄 %>
      <%= f.text_field :followup, class: 'form-control' %>

      <%= f.label :エビデンス提出 %>
      <%= f.text_field :evidence_update, class: 'form-control' %>

      <%= f.label :その他全体チェック %>
      <%= f.text_field :overall_check, class: 'form-control' %>

      <%= f.label :品質管理用ステータス %>
      <%= f.text_field :quality_status, class: 'form-control' %>

      <%= f.label :恒久実施予定日 %>
      <%= f.text_field :permanent_planday, class: 'form-control' %>

      <%= f.label :再発防止予定日 %>
      <%= f.text_field :recurrence_Preventday, class: 'form-control' %>

      <br>
      <%= f.submit yield(:button_text), class: "btn btn-lg btn-primary" %>
      <br><br>
      <%= link_to "戻る", systemfailures_path, class: "btn btn-lg btn-primary btn-block" %>
    <% end %>
  </div>

app/views/systemfailures/_systemfailure.html.erb
<tr>

<td><%= link_to "更新", edit_systemfailure_path(systemfailure), class: "btn btn-primary btn-xs"%></td>
<td><%= systemfailure.systemfailure_number %></td>
<td><%= systemfailure.subsystem_name %></td>
<td><%= systemfailure.time %></td>
<td><%= systemfailure.occur_date.strftime('%Y/%m/%d') %></td>
<td><%= systemfailure.title %></td>
<td><%= systemfailure.department %></td>
<td><%= systemfailure.reporter %></td>
<td><%= systemfailure.update_deadline ? systemfailure.update_deadline.strftime('%Y/%m/%d') : "" %></td>
<td><%= systemfailure.confirm_deadline ? systemfailure.confirm_deadline.strftime('%Y/%m/%d') : "" %></td>
<td><%= systemfailure.occur_date ? ((Date.today - Date.parse(systemfailure.occur_date.to_s)).to_i).to_s + "日" : "" %></td>

<td><%= systemfailure.signal %></td>
<td><%= systemfailure.status %></td>
<td><%= systemfailure.hayakawa_comment %></td>
<td><%= systemfailure.chargecomment %></td>
<td><%= systemfailure.exchange_status %></td>
<td><%= systemfailure.hayakawa_show %></td>
<td><%= systemfailure.report_path %></td>
<td><%= systemfailure.followup %></td>
<td><%= systemfailure.evidence_update %></td>
<td><%= systemfailure.overall_check %></td>
<td><%= systemfailure.quality_status %></td>
<td><%= systemfailure.occurrence_year + "/" + systemfailure.occurrence_month %></td>
<td><%= systemfailure.permanent_planday ? systemfailure.permanent_planday.strftime('%Y/%m/%d') : "" %></td>
<td><%= systemfailure.recurrence_Preventday ? systemfailure.recurrence_Preventday.strftime('%Y/%m/%d') : "" %></td>

</tr>

app/views/systemfailures/edit.html.erb
<% provide(:title, "Config編集") %>
<% provide(:button_text, '保存') %>
<h1>configを更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/systemfailures/index.html.erb
<% provide(:title, 'Config管理') %>
<h1>Config管理</h1>
<script type="text/javascript" class="init">
$(document).ready(function() {
	var table = $('#example').DataTable( {
		"scrollY": "600px",
		"paging": false
	} );

	$('a.toggle-vis').on( 'click', function (e) {
		e.preventDefault();

		// Get the column API object
		var column = table.column( $(this).attr('data-column') );

		// Toggle the visibility
		column.visible( ! column.visible() );
	} );

        var arr = ["15","16","17","18","19","20","21","22","23"];
        $.each(arr,function(i,value)
        {
           var objid = "#col"+value;
           $(objid).click();
        });
} );

$(document).ready(function() { 
  $( ".sample_select2" ).select2({
    width: 600,
    multiple: true
   });
});

</script>
<%= form_tag systemfailures_path, :method => 'get' do %>
<table border="1">
  <tr valign = "middle">
    <td>
      <%= link_to "新規作成", new_systemfailure_path, class: "btn btn-primary btn-xm"  %>
    </td>
  </tr>
  <tr valign = "middle">
    <td>
      <table>
        <tr>
          <td>
            <%= select_tag "selectuser", options_from_collection_for_select(@users, "name", "name"),{ class: 'sample_select2', multiple: true } %>
          </td>
          <td>
            <%= submit_tag "検索", class: "col-2 bg-primary h-50" %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>表示切替:
      <br>
      <a id = "col1" class="toggle-vis" data-column="1">障害番号</a>・
      <a id = "col2" class="toggle-vis" data-column="2">サブシステム</a>・
      <a id = "col3" class="toggle-vis" data-column="3">時点</a>・
      <a id = "col4" class="toggle-vis" data-column="4">発生日時</a>・
      <a id = "col5" class="toggle-vis" data-column="5">表題</a>・
      <a id = "col6" class="toggle-vis" data-column="6">部署</a>・
      <a id = "col7" class="toggle-vis" data-column="7">報告者</a>・
      <a id = "col8" class="toggle-vis" data-column="8">記入期限</a>・
      <a id = "col9" class="toggle-vis" data-column="9">確定期限</a>・
      <a id = "col10" class="toggle-vis" data-column="10">経過日数</a>・
      <a id = "col11" class="toggle-vis" data-column="11">シグナル</a>・
      <a id = "co112" class="toggle-vis" data-column="12">ステータス</a>・
      <a id = "col13" class="toggle-vis" data-column="13">早川さんコメント欄</a>・
      <a id = "col14" class="toggle-vis" data-column="14">担当コメント欄</a>
      <br>
      <a id = "col15" class="toggle-vis" data-column="15">やりとりステータス</a>・
      <a id = "col16" class="toggle-vis" data-column="16">早川さんにご覧いただき</a>・
      <a id = "col17" class="toggle-vis" data-column="17">報告書保存先</a>・
      <a id = "col18" class="toggle-vis" data-column="18">フォローアップ欄</a>・
      <a id = "col19" class="toggle-vis" data-column="19">エビデンス提出</a>・
      <a id = "col20" class="toggle-vis" data-column="20">その他全体チェック</a>・
      <a id = "col21" class="toggle-vis" data-column="21">品質管理用ステータス</a>・
      <a id = "col22" class="toggle-vis" data-column="22">恒久実施予定日</a>・
      <a id = "col23" class="toggle-vis" data-column="23">再発防止予定日</a>
    </td>
  </tr>
  <tr>
    <td>
      <div class="pjbox">
      <table id="example" class="display" >
        <thead>
          <tr>
            <th>更新</th>
            <th nowrap>障害番号</th>
            <th nowrap>サブシステム</th>
            <th nowrap>時点</th>
            <th nowrap>発生日時</th>
            <th nowrap>表題</th>
            <th nowrap>部署</th>
            <th nowrap>報告者</th>
            <th nowrap>記入期限</th>
            <th nowrap>確定期限</th>
            <th nowrap>経過日数</th>
            <th nowrap>シグナル</th>
            <th nowrap>ステータス</th>
            <th nowrap>早川さんコメント欄</th>
            <th nowrap>担当コメント欄</th>
            <th nowrap>やりとりステータス</th>
            <th>早川さんにご覧いただき</th>
            <th nowrap>報告書保存先</th>
            <th nowrap>フォローアップ欄</th>
            <th nowrap>エビデンス提出</th>
            <th nowrap>その他全体チェック</th>
            <th nowrap>品質管理用
              <br>ステータス
            </th>
            <th nowrap>発生年月</th>
            <th>恒久実施予定日</th>
            <th nowrap>再発防止予定日</th>
          </tr>
        </thead>
        <tbody>
          <%= render @systemfailures %>
        </tbody>
      </table>
    </td>
  </tr>
</table>
<% end %>

app/views/systemfailures/new.html.erb
<% provide(:title, 'Config登録') %>
<% provide(:button_text, '登録') %>
<h1>Config登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/systemfailures/systemfailureupload.html.erb
<% provide(:title, "Configアップロード") %>
<% provide(:button_text, 'インポート') %>
<h1>configをアップロード</h1>

<%= form_tag import_systemfailures_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>
<% end %>