config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  resources :rconfigs
  resources :systemfailures
  get  '/adduser',  to: 'users#new'
  get  '/systemfailureupload',  to: 'systemfailures#systemfailureupload'
  root 'static_pages#home'
  get  'static_pages/home'
  post '/adduser',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :systemfailures do
    collection { post :import }
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rconfig.rb
class Rconfig < ApplicationRecord

  validates :maincode,  presence: true, length: { maximum: 3 }, numericality: { only_integer: true,greater_than: 0, less_than: 999}

  validates :subcode,  presence: true, length: { maximum: 3 }, numericality: { only_integer: true,greater_than: 0, less_than: 999}
  def self.search(search) #self.でクラスメソッドとしている


    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      Rconfig.where(['title LIKE ?', "%#{search}%"])
    else
      Rconfig.all #全て表示。
    end
  end
end

app/controllers/rconfigs_controller.rb
class RconfigsController < ApplicationController
  before_action :admin_user, only: [:index, :edit, :update]
  
  def index
    @rconfigs = Rconfig.search(params[:search])
  end

  def show
    @rconfig = Rconfig.find(params[:id])
  end

  def new
    @rconfig = Rconfig.new
  end

  def create
    @rconfig = Rconfig.new(rconfig_params)
    if @rconfig.save
      flash[:success] = "登録成功"
      redirect_to rconfigs_path
    else
      render 'new'
    end
  end

  def edit
    @rconfig = Rconfig.find(params[:id])
  end

  def update
    @rconfig = Rconfig.find(params[:id])
    if @rconfig.update_attributes(rconfig_params)
      flash[:success] = "保存成功しました。"
      redirect_to(rconfigs_path)
    else
      render 'edit'
    end
  end

  private

    def rconfig_params
      params.require(:rconfig).permit(:maincode, :subcode, :title, :description, :deleteflg)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/views/rconfigs/_form.html.erb
    <%= form_for(@rconfig) do |f| %>
      <%= render 'shared/rconfig_error_messages' %>

      <%= f.label :メインコード %>
      <%= f.text_field :maincode , class: 'form-control'%>

      <%= f.label :サブコード %>
      <%= f.text_field :subcode, class: 'form-control' %>

      <%= f.label :タイトル %>
      <%= f.text_field :title , class: 'form-control'%>

      <%= f.label :説明 %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :表示FLG %>
      <%= f.select :deleteflg, [["表示", "表示"], ["非表示", "非表示"]],  {prompt: "選択してください"}, {class: 'form-control form-control-lg'} %>
      <br>
      <%= f.submit yield(:button_text), class: "btn btn-lg btn-primary" %>
      <br><br>
      <%= link_to "戻る", rconfigs_path, class: "btn btn-lg btn-primary btn-block" %>
    <% end %>
  </div>

app/views/rconfigs/_rconfig.html.erb
<tr>
<td><%= rconfig.maincode %></td>
<td><%= rconfig.subcode %></td>
<td><%= rconfig.title %></td>
<td><%= rconfig.description %></td>
<td><%= rconfig.deleteflg %></td>
<td><%= link_to "更新", edit_rconfig_path(rconfig), class: "btn btn-primary btn-xs"%></td>
</tr>

app/views/rconfigs/index.html.erb
<% provide(:title, 'Config管理') %>
<h1>Config管理</h1>

<%= form_tag rconfigs_path, :method => 'get' do %>
  <p>
    <table>
<tr valign = "middle">
<td><%= text_field_tag :search, params[:search], placeholder: "タイトルを入力する",class: "form-control"  %></td>
<td><%= submit_tag "検索", class: "btn btn-primary btn-sm" %></td>
<td>&emsp;</td>
<td><%= link_to "新規作成", new_rconfig_path, class: "btn btn-primary btn-sm"  %></td>
</tr>
    </table>
    
    
  </p>
<% end %>

<table class="table table-striped">
  <tr><th>メインコード</th><th>サブコード</th><th>部門タイトル</th><th>説明</th><th>表示FLG</th><th>更新</th></tr>
    <%= render @rconfigs %>
</table>
