config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  resources :rconfigs
  resources :systemfailures
  get  '/adduser',  to: 'users#new'
  get  '/systemfailureupload',  to: 'systemfailures#systemfailureupload'
  root 'static_pages#home'
  get  'static_pages/home'
  post '/adduser',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :systemfailures do
    collection { post :import }
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>xxxx-xxx</p>
  </small>
  <nav>
    <ul>
      <li><a href="http://yahoo.co.jp/">contact me</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "障害管理", root_path%>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <% if logged_in? %>
          <% if admin_user %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              システム管理 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Config管理", rconfigs_path %></li>
              <li class="divider"></li>
              <li><%= link_to "障害案件取り込み", systemfailureupload_path %></li>
              <li class="divider"></li>
              <li><%= link_to "ユーザー追加", adduser_path %></li>
              <li class="divider"></li>
              <li><%= link_to "ユーザー削除", users_path %></li>
            </ul>
          </li>
          <% end %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              ユーザー <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ユーザー設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "障害案件一覧", systemfailures_path %></li>
              <li class="divider"></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>